fix(delete): Handle case where Adfinis group does not exist
adfinis/ansible-role-users pull request #12
Opened 2023-09-28 11:28 UTC by martinwe-adfinis

This may typically happen when the role is run on a system for the first time and the Adfinis group has never been generated before.

We use the same approach as for the user creation: Attempt to gather group information and store the fact of whether the group exists or not in a variable, then conditionally do follow-up steps depending on whether we did get any information.

2023-09-28 11:30 UTC, martinwe-adfinis commented
Tested on a system that already has the `adfinis` group, does not break it.

Now needs some testing on a system where the `adfinis` group is not present yet.

Marking as bug(fix) and also to be backported to 0.3 once it's merged.

2023-09-29 12:13 UTC, aconitumnapellus requested changes

2023-09-29 12:13 UTC, aconitumnapellus commented on tasks/adfinis_delete.yml
> +        users_adfinis_all: "{{ users_register_getent_group_adfinis.ansible_facts.getent_group['adfinis'][2] | split(',') }}"
This needs a filter to weed out empty strings. Ive already created a commit and will push this commit onto this branch.

2023-09-29 12:16 UTC, aconitumnapellus approved these changes

2023-09-29 12:16 UTC, aconitumnapellus commented
With the additional commit ive made, this also works on a "naked" system now.

2023-09-29 12:18 UTC, aconitumnapellus commented on tasks/adfinis_delete.yml
> +        users_adfinis_all: "{{ users_register_getent_group_adfinis.ansible_facts.getent_group['adfinis'][2] | split(',') }}"
Ive made the necessary commit already.

2023-10-05 11:11 UTC, merged

2023-10-05 11:11 UTC, martinwe-adfinis commented
thanks!

2023-10-05 11:14 UTC, martinwe-adfinis commented
urgh, I forgot to add a changelog